/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f446xx.h"
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include "drivers/gpio.h"
#include "config/project_config.h"
#include "board/board.h"
#include "drivers/adc.h"
#include "drivers/log.h"
#include "motor/motor_6step.h"

extern volatile bool user_button_on;
//extern pwm_tim1_handle_t PWM_H;

extern usart2_handle_t USART2_H;

int __io_putchar(int ch)
{
    uint8_t c = (uint8_t)ch;
    size_t w = usart2_write(&USART2_H, &c, 1u);

    return (w == 1u) ? ch : EOF;
}

int main(void)
{
	static const motor_6step_cfg_t MOTOR_6STEP_CFG = {
		.step_period_ms = 500u,
//		.dir = MOTOR_6STEP_DIR_CW
		.dir = MOTOR_6STEP_DIR_CCW
	};

	static motor_6step_handle_t motor_6step_h = {0};

	board_init(); // drivers initialization
	log_init(&USART2_H);
	LOGI("APP", "boot");

	motor_6step_init(&motor_6step_h, &MOTOR_6STEP_CFG);
	motor_6step_start(&motor_6step_h, SYSTICK_GetTimeMs());
	LOGI("M6", "6-step state machine started");

	/* Loop forever */
	while(1)
	{
		static uint32_t last_log_ms = 0u;
		uint32_t now_ms = SYSTICK_GetTimeMs();

		if (motor_6step_update(&motor_6step_h, now_ms))
		{
			motor_6step_phase_map_t phase_map = motor_6step_get_phase_map(&motor_6step_h);

			/* M6: 6-step commutation state machine */
			LOGI_F("M6", "step=%u dir=%u state=%u A=%u B=%u C=%u",
				   (unsigned)motor_6step_get_step(&motor_6step_h),
				   (unsigned)motor_6step_get_dir(&motor_6step_h),
				   (unsigned)motor_6step_get_state(&motor_6step_h),
				   (unsigned)phase_map.phase_a,
				   (unsigned)phase_map.phase_b,
				   (unsigned)phase_map.phase_c);

			/* sample_id = 1: 6-step phase sequence sample */
			log_data_u32(1u,
						 (uint32_t)motor_6step_get_step(&motor_6step_h),
						 (uint32_t)motor_6step_get_dir(&motor_6step_h),
						 (uint32_t)motor_6step_get_state(&motor_6step_h),
						 MOTOR_6STEP_CFG.step_period_ms);
		}

		if ((now_ms - last_log_ms) >= 1000u)
		{
			last_log_ms = now_ms;

			/* HB: periodic heartbeat log */
			LOGI_F("HB", "tx_drop=%u rx_drop=%u ore=%lu",
				   (unsigned)USART2_H.tx_buffer->drop_cnt,
				   (unsigned)USART2_H.rx_buffer->drop_cnt,
				   (unsigned long)USART2_H.err_ore_cnt);
		}
	}
}
