/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f446xx.h"
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include "drivers/gpio.h"
#include "config/project_config.h"
#include "board/board.h"
#include "drivers/adc.h"
#include "drivers/log.h"
#include "motor/motor_6step.h"
#include "motor/motor_driver.h"

extern usart2_handle_t USART2_H;

int __io_putchar(int ch)
{
    uint8_t c = (uint8_t)ch;
    size_t w = usart2_write(&USART2_H, &c, 1u);

    return (w == 1u) ? ch : EOF;
}

int main(void)
{
	board_init(); // drivers initialization
	log_init(&USART2_H);
	LOGI("APP", "boot");

	if (!motor_6step_init(&MOTOR_6STEP_H, &MOTOR_6STEP_CFG))
	{
		LOGE("M6", "init failed");
		while (1) {}
	}

	if (!motor_driver_init(&MOTOR_DRIVER_H, &MOTOR_DRIVER_CFG))
	{
		LOGE("MDRV", "init failed");
		while (1) {}
	}

	motor_6step_start(&MOTOR_6STEP_H, SYSTICK_GetTimeMs());

	motor_6step_phase_map_t phase_map = motor_6step_get_phase_map(&MOTOR_6STEP_H);
	if (!motor_driver_apply_phase_map(&MOTOR_DRIVER_H, &phase_map))
	{
		LOGE("MDRV", "apply failed");
		while (1) {}
	}

	if (!motor_driver_start(&MOTOR_DRIVER_H))
	{
		LOGE("MDRV", "start failed");
		while (1) {}
	}
	
	LOGI("M6", "6-step state machine started");
	LOGI("MDRV", "PWM output started");

	/* Loop forever */
	while(1)
	{
		static uint32_t last_log_ms = 0u;
		uint32_t now_ms = SYSTICK_GetTimeMs();

		if (motor_6step_update(&MOTOR_6STEP_H, now_ms))
		{
			motor_6step_phase_map_t phase_map = motor_6step_get_phase_map(&MOTOR_6STEP_H);

			if (!motor_driver_apply_phase_map(&MOTOR_DRIVER_H, &phase_map))
			{
				LOGE("MDRV", "apply failed");
				while (1) {}
			}

			motor_driver_cmd_map_t cmd_map = motor_driver_get_cmd_map(&MOTOR_DRIVER_H);
			
			/* M6: 6-step commutation state machine */
			LOGI_F("M6", "step=%u dir=%u state=%u A=%u B=%u C=%u",
				   (unsigned)motor_6step_get_step(&MOTOR_6STEP_H),
				   (unsigned)motor_6step_get_dir(&MOTOR_6STEP_H),
				   (unsigned)motor_6step_get_state(&MOTOR_6STEP_H),
				   (unsigned)cmd_map.phase_a,
				   (unsigned)cmd_map.phase_b,
				   (unsigned)cmd_map.phase_c);

			/* sample_id = 1: 6-step driver command sample */
			log_data_u32(1u,
						 (uint32_t)motor_6step_get_step(&MOTOR_6STEP_H),
						 (uint32_t)cmd_map.phase_a,
						 (uint32_t)cmd_map.phase_b,
						 (uint32_t)cmd_map.phase_c);
		}

		if ((now_ms - last_log_ms) >= 1000u)
		{
			last_log_ms = now_ms;

			/* HB: periodic heartbeat log */
			LOGI_F("HB", "tx_drop=%u rx_drop=%u ore=%lu",
				   (unsigned)USART2_H.tx_buffer->drop_cnt,
				   (unsigned)USART2_H.rx_buffer->drop_cnt,
				   (unsigned long)USART2_H.err_ore_cnt);
		}
	}
}
